# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZ3HognV45FrHgwySmfFWQHvzu1nlxlb
"""

!apt-get update -qq
!apt-get install fonts-nanum -qq

import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

print(" 폰트 설정 완료! 다시 그래프 실행하세요.")

import requests
import pandas as pd
import textwrap
from IPython.display import Image, display

api_key = ""
base_url = "https://api.themoviedb.org/3"
poster_url = "https://image.tmdb.org/t/p/w500"

def get_story(title):
    url = f"{base_url}/search/movie?api_key={api_key}&query={title}&language=ko-KR"
    res = requests.get(url).json()

    if res['results']:
        movie = res['results'][0]
        print("\n==============================")
        print(f" 제목 : {movie['title']}")
        print(f" 개봉일 : {movie.get('release_date', '정보없음')}")
        print(f" 평점 : {movie['vote_average']}")

        print("\n📖 줄거리:\n")
        overview = movie.get('overview', '줄거리 없음')
        wrapped_text = textwrap.fill(overview, width=40)
        print(wrapped_text)

        print("\n==============================")

        if movie.get('poster_path'):
            display(Image(url=poster_url + movie['poster_path']))

    else:
        print("\n 해당 영화가 없습니다.")

def genre_recommend(code):
    url = f"{base_url}/discover/movie?api_key={api_key}&with_genres={code}&sort_by=vote_average.desc&vote_count.gte=200&language=ko-KR"
    res = requests.get(url).json()

    print("\n 추천 영화 Top5\n")
    for i, m in enumerate(res['results'][:5],1):
        print(f"{i}. {m['title']}  ⭐{m['vote_average']}")
    print("\n==============================\n")

def run():
    user = input("영화 제목 또는 장르 추천 입력 : ")

    genre_dict = {
        "공포":27,"호러":27,
        "로맨스":10749,"멜로":10749,"사랑":10749,
        "코미디":35,
        "액션":28,
        "드라마":18,
        "스릴러":53,
        "SF":878,"과학":878,
        "판타지":14,
        "전쟁":10752,
        "모험":12,
    }

    for k,v in genre_dict.items():
        if k in user:
            print(f"\n🎥 '{k}' 영화 추천 결과\n")
            genre_recommend(v)
            return

    get_story(user)

run()
